#ifndef WORLD_CONSTANTS_H
#define WORLD_CONSTANTS_H

constexpr int CHUNK_SIZE = 16, CHUNK_AREA = CHUNK_SIZE * CHUNK_SIZE,
CHUNK_VOLUME = CHUNK_AREA * 64, LOAD_DISTANCE = 2, RENDER_DISTANCE = 2;

#endif