#ifndef WORLD_CONSTANTS_H
#define WORLD_CONSTANTS_H

constexpr int CHUNK_SIZE = 16, CHUNK_AREA = CHUNK_SIZE * CHUNK_SIZE,
CHUNK_VOLUME = CHUNK_AREA * CHUNK_SIZE, LOAD_DISTANCE = 4, RENDER_DISTANCE = 4;

constexpr int MAX_HEIGHT = 256;

#endif